project: "iexp associativity"

# training/eval
batch_size: 128
max_buffer_episodes: 5000
z_inference_steps: 10000
discount: 0.98
eval_frequency: 10000  # how often to evaluate the agent in learning steps
eval_rollouts: 10  # how many rollouts to average over when evaluating

# forward-backward
name: "test"
save_dir: "/home/tsinghuaair/zhengkx/conservative-world-models/agents/iexp/saved_models"
preprocessor_hidden_dimension: 1024
preprocessor_hidden_layers: 2
preprocessor_output_dimension: 512
preprocessor_activation: "relu"

z_dimension: 50

forward_hidden_dimension: 256
forward_hidden_layers: 2
forward_number_of_features: 2  # {obs-action, obs-z}
forward_activation: "relu"

backward_preprocess: False
backward_preprocess_output_dimension: 512
backward_preprocess_hidden_layers: 1
backward_preprocess_activation: "relu"
backward_preprocess_hidden_dimension: 1024
backward_hidden_dimension: 256
backward_hidden_layers: 3
backward_activation: "relu"

use_trans: true
use_kan: false
kan_config:
  width: [100, 512, 128, 1]
  grid: 5 
  k: 3
  noise_scale: 0.1
  noise_scale_base: 0.1

use_res: false
use_fed: false
use_VIB: false
use_2branch: false
use_q_loss: false
use_AWAR: false
q_coefficient: 1
operator_hidden_dimension: 512
operator_hidden_layers: 3
operator_activation: "relu"

mul_trans: false
trans_hidden_dimension: 256
use_cross_attention: true
num_attention_heads: 1
n_attention_layers: 2
n_linear_layers: 2
dropout_rate: 0.1

actor_hidden_dimension: 1024
actor_hidden_layers: 2
actor_activation: "relu"

seed: 42
critic_learning_rate: 0.000001
actor_learning_rate: 0.00005
learning_steps: 1000000
f_loss_coefficient: 5
b_learning_rate_coefficient: 1
g_learning_rate_coefficient: 1
orthonormalisation_coefficient: 1
z_mix_ratio: 0.5
gaussian_actor: false
std_dev_clip: 0.3
std_dev_schedule: "0.2"
std_dev_eval: 0.05
tau: 0.01
asymmetric_l2_tau: 0.9


use_associativity_loss: false
associativity_loss_coefficient: 100