# training/eval
batch_size: 2048
max_buffer_episodes: 5000
z_inference_steps: 10000
discount: 0.98
eval_frequency: 10000  # how often to evaluate the agent in learning steps
eval_rollouts: 10  # how many rollouts to average over when evaluating
project: "walker-rnd"

# forward-backward
name: "iexp critic8e-5 actor5e-5"
save_dir: "./agents/iexp/walker"
preprocessor_hidden_dimension: 1024
preprocessor_hidden_layers: 2
preprocessor_output_dimension: 512
preprocessor_activation: "relu"

z_dimension: 50

forward_hidden_dimension: 256
forward_hidden_layers: 2
forward_number_of_features: 2  # {obs-action, obs-z}
forward_activation: "relu"

backward_preprocess: False
backward_preprocess_output_dimension: 512
backward_preprocess_hidden_layers: 1
backward_preprocess_activation: "relu"
backward_preprocess_hidden_dimension: 1024
backward_hidden_dimension: 256
backward_hidden_layers: 3
backward_activation: "relu"

use_trans: true
use_diffusion: true
use_res: false
use_fed: false
use_VIB: false
use_sql: false
use_eql: false
use_2branch: false
use_linear_res: false
use_feature_norm: false
use_AWAR: false
operator_hidden_dimension: 512
operator_hidden_layers: 3
operator_activation: "relu"

mul_trans: false
trans_hidden_dimension: 256
use_cross_attention: true
num_attention_heads: 1
n_attention_layers: 2
n_linear_layers: 2
dropout_rate: 0.1

actor_hidden_dimension: 1024
actor_hidden_layers: 2
actor_activation: "relu"

seed: 42
critic_learning_rate: 0.00008
actor_learning_rate: 0.00005
learning_steps: 1000000
b_learning_rate_coefficient: 1
g_learning_rate_coefficient: 1
orthonormalisation_coefficient: 1
z_mix_ratio: 0.5
gaussian_actor: true
std_dev_clip: 0.3
std_dev_schedule: "0.2"
std_dev_eval: 0.05
tau: 0.001
iql_tau: 0.9
beta: 3
ts: 5
alpha: 2